### ISSUE TITLE
UN Marathi sample is wrong

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#11]
Our site:

<img width="310" alt="Screen Shot 2020-10-15 at 12 15 45 PM" src="https://user-images.githubusercontent.com/11865/96076544-291a8880-0ee0-11eb-82f7-d8b2895d6310.png">

Original poster:
<img width="269" alt="Screen Shot 2020-10-15 at 12 15 58 PM" src="https://user-images.githubusercontent.com/11865/96076550-2fa90000-0ee0-11eb-9c2a-bfd05f06d160.png">

@bilashsaha could you help update it? Thanks!

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/578

**Comment by bilashsaha** [comment]
@ronaldtse The [rule](https://www.eki.ee/wgrs/rom1_mr.pdf) follows hindi with some extra rules for marathi. In the hindi rule we have 
```
It is recommended that the vowel अ (a) should always be romanized except when it ends a name
```
Now `महाराष्ट्र` is also a name of the one of the state of India, which should not end with `a` as per the rule but in this example its been shown to be ended with `a`. In our corrected transliteration, it matches with `mahārāṣhṭr` - the first letters but the last `a` is removed as per the rule. I have added this examples to our system as well.

```
  - source: "महाराष्ट्र"
    expected: "mahārāṣhṭr"
  - source: "मुंबई"
    expected: "muṁbaī"
```

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/578

**Comment by ronaldtse** [comment]
All merged, pending gem release and update.

**Comment by ronaldtse** [comment]
Fixed.
<img width="334" alt="Screen Shot 2020-11-23 at 3 40 46 PM" src="https://user-images.githubusercontent.com/11865/99938200-41fd4000-2da2-11eb-9e11-0002fec30ae3.png">
