### ISSUE TITLE
UN Chinese using wrong transliteration system

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#12]
Site:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/11865/96076636-5ff09e80-0ee0-11eb-8f68-786fe8447572.png">

Original:
<img width="221" alt="Screen Shot 2020-10-15 at 12 17 41 PM" src="https://user-images.githubusercontent.com/11865/96076655-6d0d8d80-0ee0-11eb-92b8-5fb443539d45.png">

Should be using sac-pinyin system.

**Comment by webdev778** [comment]
ok
