### ISSUE TITLE
UN Kannada system different

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#15]
Interscript: 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/11865/96076804-cc6b9d80-0ee0-11eb-89f1-a3d71d433c56.png">

UN:
<img width="276" alt="Screen Shot 2020-10-15 at 12 20 28 PM" src="https://user-images.githubusercontent.com/11865/96076809-d2617e80-0ee0-11eb-86d7-79f7048f90ec.png">

Ping @bilashsaha

**Comment by bilashsaha** [comment]
@ronaldtse We do not cover `un-kan-Knda-Latn` [system](https://www.eki.ee/wgrs/rom1_kn.pdf) yet. Is this the output of `iso-kan-Knda-Latn-15919-2001` ? I had added a new issue : https://github.com/interscript/interscript/issues/580 to add this and will work on this.

**Comment by ronaldtse** [comment]
@bilashsaha you're right, it's actually using the BIS system:

https://github.com/interscript/jsdemo.interscript.com/blob/eda83fde7e67b35ac06464e48a422ca920abefa5/src/samples/samples.json#L124-L130

Could you help fix this once we have the UN system? The lines about are what needs to be changed. Thanks!

**Comment by bilashsaha** [comment]
@ronaldtse Please have a look at : https://github.com/interscript/interscript/pull/586 and then https://github.com/interscript/jsdemo.interscript.com/pull/34

**Comment by ronaldtse** [comment]
All merged. The site isn't showing it yet because we need to release a new gem to trigger the subsequent interscript-js release and the redeploy.

**Comment by ronaldtse** [comment]
Fixed.

<img width="341" alt="Screen Shot 2020-11-23 at 3 39 32 PM" src="https://user-images.githubusercontent.com/11865/99938099-15e1bf00-2da2-11eb-9c05-37e2fc7d7078.png">
