### ISSUE TITLE
UN Nepali system different

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#16]
Interscript:
<img width="326" alt="Screen Shot 2020-10-15 at 12 21 09 PM" src="https://user-images.githubusercontent.com/11865/96076846-ead19900-0ee0-11eb-8ac2-5b01ca844f93.png">

Original:
<img width="322" alt="Screen Shot 2020-10-15 at 12 21 28 PM" src="https://user-images.githubusercontent.com/11865/96076858-f3c26a80-0ee0-11eb-8a77-da3a2f88dfb6.png">

Ping @bilashsaha @rabinshrestha

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/559

**Comment by bilashsaha** [comment]
PR : https://github.com/interscript/interscript/pull/576

**Comment by ronaldtse** [comment]
All merged, need to wait for redeploy of jsdemo.interscript.com

**Comment by ronaldtse** [comment]
This is now fixed, thanks!
