### ISSUE TITLE
UN Oriya system different

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#17]
Interscript:
<img width="280" alt="Screen Shot 2020-10-15 at 12 22 47 PM" src="https://user-images.githubusercontent.com/11865/96076957-25d3cc80-0ee1-11eb-8627-f1dd144abd12.png">

Original:
<img width="262" alt="Screen Shot 2020-10-15 at 12 23 06 PM" src="https://user-images.githubusercontent.com/11865/96076972-2e2c0780-0ee1-11eb-9ca3-8eb9065fd34e.png">

There are typos in the sample.

**Comment by bilashsaha** [comment]
@ronaldtse The [mapping](https://github.com/interscript/jsdemo.interscript.com/blob/master/src/samples/un.json#L211-L216) is wrong and we need to implement this [system](https://www.eki.ee/knab/lat/kblor2.pdf) into interscript. I have made this [issue](https://github.com/interscript/interscript/issues/591) for this one and started working on it.

**Comment by ronaldtse** [comment]
Got it, in this case please help update the JS mapping once the system is created. Thanks!

**Comment by ronaldtse** [comment]
Will leave this ticket open until it's fixed.

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/jsdemo.interscript.com/pull/36

**Comment by ronaldtse** [comment]
@bilashsaha merged and pending site update.

**Comment by ronaldtse** [comment]
Fixed.
<img width="303" alt="Screen Shot 2020-11-23 at 3 39 12 PM" src="https://user-images.githubusercontent.com/11865/99938073-0a8e9380-2da2-11eb-8669-aa659e63d06a.png">
