### ISSUE TITLE
SSR pages should be generated dynamically on the site build process, should not require entering result

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#38]
1. The SSR pages are identical to the dynamic ones
2. Since the build process can utilize Interscript, we can build those dynamically without needing to hard code the "results".

=> Then we do not need to have 2 files for every page.

**Comment by webdev778** [comment]
Yeah, it was a temporary solution. let me fix it

**Comment by webdev778** [comment]
Fix #39
