### ISSUE TITLE
Add OGC 11-122r1 compatibility poster page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#4]
This depends on functionality of https://github.com/interscript/interscript/issues/527

Full list here:
interscript/interscript#527

------

Systems with content

tir_Thai2Latn_RIT_2000
zho_Hani2Latn_GCH_1979
fas_Arab2Latn_BGN_1958
ara_Arab2Latn_BGN_1956
rus_Cyrl2Latn_BGN_1947
kor_Hang2Latn_MOCT_2000
jpn_Hrkt2Latn_BGN_1930
hye_Armn2Latn_BGN_1981
ell_Grek2Latn_ELOT743_1996
mkd_Cyrl2Latn_BGN_2013
kor_Hang2Latn_MR_1939
ukr_Cyrl2Latn_BGN_1965
heb_Hebr2Latn_HAS_1962
kaz_Cyrl2Latn_BGN_1979
bul_Cyrl2Latn_BGN_2013
kur_Arab2Latn_BGN_1931
ukr_Cyrl2Latn_BGN_2019
kat_Geor2Latn_GGG_2002
khm_Khmr2Latn_SGK_1959
bel_Cyrl2Latn_BGN_1979
uas_Arab2Latn_BGN_2007
tgk_Cyrl2Latn_BGN_1994
srp_Cyrl2Latn_BGN_2005
kat_Geor2Latn_BGN_1981
heb_Hebr2Latn_BGN_2018
che_Cyrl2Latn_BGN_2007
fas_Arab2Latn_ALA_1997
hye_Armn2Latn_ALA_1997
ara_Arab2Latn_ALA_1997
mkd_Cyrl2Latn_BGN_1981
rus_Cyrl2Latn_ALA_1997
kir_Cyrl2Latn_BGN_1979
jpn_Hrkt2Latn_GJP_1954
mon_Cyrl2Latn_BGN_1964
fas_Arab2Latn_NCO_2004
urd_Arab2Latn_BGN_2007
fas_Arab2Latn_AMMI_1959
rus_Cyrl2Latn_GOST_1983
heb_Hebr2Latn_ALA_1997
ukr_Cyrl2Latn_ALA_1997
kat_Geor2Latn_ALA_1997
jpn_Hrkt2Latn_ALA_1997
zho_Hani2Latn_ALA_1997
uig_Arab2Latn_UCIS_2001
tir_Ethi2Latn_ALA_1997
bel_Cyrl2Latn_ALA_1997
amh_Ethi2Latn_BGN_1967
fao_Latn2Latn_BGN_1968
ara_Arab2Latn_BUC_2002
pus_Arab2Latn_BGN_1968
khm_Khmr2Latn_ALA_1997
ukr_Cyrl2Latn_GUP_1996
tha_Thai2Latn_ALA_1997
tir_Ethi2Latn_BGN_2007
zho_Hani2Latn_WDG_1979
jav_Java2Latn_ALA_1997
kur_Arab2Latn_ALA_1997
mon_Cyrl2Latn_ALA_1997
tha_Thai2Latn_RIT_1968
bel_Cyrl2Latn_GBO_1998
srp_Cyrl2Latn_ALA_1997
ell_Grek2Latn_BGN_1962
bel_Cyrl2Latn_GBO_1992
aze_Cyrl2Latn_GAZ_1991
ukr_Cyrl2Latn_ODNI_2005
fas_Arab2Latn_ODNI_2004
aze_Cyrl2Latn_ALA_1997
zho_Hani2Latn_AcadSin_2002
tuk_Cyrl2Latn_BGN_1979
srp_Cyrl2Latn_ODNI_2005
amh_Ethi2Latn_ALA_1997
hin_Deva2Latn_ALA_1997
ara_Arab2Latn_RJGC_1996
kor_Hang2Latn_ALA_1997
kur_Arab2Latn_EDMONDS_1931
ara_Arab2Latn_IGN_1973
bul_Cyrl2Latn_BGN_1952

-----

Empty systems

bod_Tibt2Latn_ALA_1997
div_Thaa2Latn_GMV_1988
dzo_Tibt2Latn_GBT_1994
lao_Laoo2Latn_ALA_1997
lao_Laoo2Latn_CNT_1966
nep_Mymr2Latn_BGN_1970
ori_Orya2Latn_ALA_1997
pan_Deva2Latn_ALA_1997
rue_Cyrl2Latn_BGN_2016
rus_Cyrl2Latn_ODNI_2004
uig_Arab2Latn_XLSC_1959
urd_Arab2Latn_HUN_
uzb_Cyrl2Latn_BGN_1979

**Comment by ronaldtse** [comment]
For the poster page we can just provide the first test from every system as "example".

**Comment by webdev778** [comment]
PR #30
