### ISSUE TITLE
If a system has multiple "year editions", only show the latest, add a switch to change years

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#40]
e.g. BGN/PCGN https://jsdemo.interscript.com/bgnpcgn

Now:
<img width="281" alt="Screen Shot 2020-11-17 at 11 46 23 AM" src="https://user-images.githubusercontent.com/11865/99344229-85e7d500-28ca-11eb-8958-6e114550f891.png">

With switch:
<img width="361" alt="Screen Shot 2020-11-17 at 11 48 11 AM" src="https://user-images.githubusercontent.com/11865/99344332-c6dfe980-28ca-11eb-9667-323149313494.png">

**Comment by webdev778** [comment]
Ok, if the year link's clicked, it should show the result for that year?

**Comment by ronaldtse** [comment]
Yes please.
