### ISSUE TITLE
Update BGN/PCGN poster page list systems according to official list

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#41]
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/921738/INTRODUCTION.pdf

List copied out here in order:

Abkhaz
Adyghe
Afghanistan
Bulgarian
Burmese
Amharic
Arabic
Armenian
Avar
Azerbaijani
Baluchi
Bashkir
Belarusian
Dzongkha
Chechen
Chinese Pinyin
Chuvash
Faroese
Georgian
German
Greek ELOT 743
Hebrew
Icelandic
Inuktitut
Japanese Kana Modified Hepburn
Kabardian
Karachay-Balkar
Kazakh
Khmer (Cambodian)
Korean Ministry of Culture and Tourism (for Republic of Korea)
Korean McCune-Reischauer (for Democratic People’s Republic of Korea)
Kurdish
Kyrgyz
Lao
Macedonian
Maldivian
Moldovan
Mongolian
Nepali
Northern Sami
Ossetian
Pashto
Persian (Dari)
Persian (Farsi)
Russian
Rusyn
Serbian
Shan
Syriac
Tajik
Tatar
Thai
Tigrinya
Turkmen
Udmurt
Ukrainian
Urdu
Uzbek
Yakut

**Comment by webdev778** [comment]
Ok, Sure

**Comment by webdev778** [comment]
where did you copy the list above, I checked the pdf file but I couldn't find it anywhere. maybe you meant the table at the bottom? it looks different. please clarify this. thanks
