### ISSUE TITLE
BGN poster page: Armenian 1981 listed twice

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#44]
![image](https://user-images.githubusercontent.com/11865/99937861-9a800d80-2da1-11eb-9495-05f347c54d28.png)

**Comment by webdev778** [comment]
Fixed on this [commit](https://github.com/interscript/jsdemo.interscript.com/commit/bc32698233f9c3f58f79ef5bb3ebaff6273e23a3)

**Comment by ronaldtse** [comment]
Thanks!
