### ISSUE TITLE
BGN poster page: highlight (bold or underline) currently selected system-year

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#45]
![image](https://user-images.githubusercontent.com/11865/99937904-b2579180-2da1-11eb-9c5a-fad89f719ca9.png)

**Comment by webdev778** [comment]
Fixed with this [commit](https://github.com/interscript/jsdemo.interscript.com/commit/bc32698233f9c3f58f79ef5bb3ebaff6273e23a3)

**Comment by ronaldtse** [comment]
Thanks!
