### ISSUE TITLE
Poster pages (BGN, etc): remove trailing whitespace after system-year

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#46]
![image](https://user-images.githubusercontent.com/11865/99937960-d1562380-2da1-11eb-81b2-6f5aa6a72ae4.png)

**Comment by webdev778** [comment]
Fixed with this [commit](https://github.com/interscript/jsdemo.interscript.com/commit/bc32698233f9c3f58f79ef5bb3ebaff6273e23a3)

**Comment by ronaldtse** [comment]
Thanks @webdev778 !
