### ISSUE TITLE
OGC poster page should show OGC code

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#48]
We should use the OGC 11-122 codes instead of "OGC [YYYY]"

i.e. instead of this:

<img width="197" alt="Screen Shot 2020-11-25 at 10 36 50 AM" src="https://user-images.githubusercontent.com/11865/100175850-214ffa00-2f0a-11eb-8f45-ff508b690df8.png">

it should be:

<img width="294" alt="Screen Shot 2020-11-25 at 10 37 50 AM" src="https://user-images.githubusercontent.com/11865/100175925-45abd680-2f0a-11eb-817a-fb8b0d455c26.png">

**Comment by webdev778** [comment]
Let me check
