### ISSUE TITLE
Add ODNI poster page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#5]
Similar to interscript/interscript.com#10 , we should make an ODNI poster page with samples.

Systems available: https://github.com/interscript/interscript/issues/496

**Comment by webdev778** [comment]
#453 odni-kur-Cyrl-Latn-standard-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)
#452 odni-kur-Arab-Latn-standard-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)
#283 odni-kur-Arab-Latn-unique-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)
#282 odni-kur-Arab-Latn-kurdish-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)
#281 odni-kur-Latn-Latn-romanized-kurmanji-to-standard-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)
#280 odni-kur-Cyrl-Latn-2015 (ODNI Kurdish Personal Names 2015 System, ICS-630-01 Annex G)

Please make sure those Kurdish systems are different each other cuz looks like same each other
#453 looks like same as #280

**Comment by webdev778** [comment]
Add Example poster page #27
