### ISSUE TITLE
UN poster page: Persian [UN 1967, I/13]

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#56]
This system has been implemented in interscript/interscript#568.

The UN page is not showing it.
<img width="298" alt="Screen Shot 2020-12-06 at 2 06 04 PM" src="https://user-images.githubusercontent.com/11865/101272983-2e9f9b00-37cc-11eb-98f3-0b9444dd42e1.png">

**Comment by webdev778** [comment]
it seems not working properly
* js 
![image](https://user-images.githubusercontent.com/28761746/101859730-a0eaf380-3baf-11eb-9028-6e176716539b.png)

* ruby 
![image](https://user-images.githubusercontent.com/28761746/101859754-aba58880-3baf-11eb-9ff2-4b0627ac7c28.png)
![image](https://user-images.githubusercontent.com/28761746/101859756-ae07e280-3baf-11eb-9963-cea9cce69fd8.png)

**Comment by ronaldtse** [comment]
Ping @AhMohsen46 , maybe the diacritics are not set correctly?
