### ISSUE TITLE
UN poster page: Ukrainian implemented but not shown

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#58]
On page:

<img width="299" alt="Screen Shot 2020-12-06 at 3 03 14 PM" src="https://user-images.githubusercontent.com/11865/101273856-2ba8a880-37d4-11eb-9828-6088957e92a5.png">

The system was implemented in interscript/interscript#295.

**Comment by webdev778** [comment]
The result:
![image](https://user-images.githubusercontent.com/28761746/101859980-1787f100-3bb0-11eb-95d7-6a476e5731a9.png)

The UN poster doc:
![image](https://user-images.githubusercontent.com/28761746/101860005-2a022a80-3bb0-11eb-8be6-9db1f80cdfe1.png)

**Comment by ronaldtse** [comment]
Ping @CAMOBAP for correctness of the system. Thanks!
