### ISSUE TITLE
Add ALA/LC poster page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#6]
Similar to interscript/interscript.com#10 , we should make an ALA/LC poster page with samples.

**Comment by webdev778** [comment]
Total 41 in the current version.

alalc-amh-Ethi-Latn-1997.yaml
alalc-amh-Ethi-Latn-2011.yaml
alalc-ara-Arab-Latn-1997.yaml
alalc-asm-Deva-Latn-1997.yaml
alalc-asm-Deva-Latn-2012.yaml
alalc-aze-Cyrl-Latn-1997.yaml
alalc-bel-Cyrl-Latn-1997.yaml
alalc-ben-Beng-Latn-2017.yaml
alalc-bul-Cyrl-Latn-1997.yaml
alalc-ell-Grek-Latn-1997.yaml
alalc-ell-Grek-Latn-2010.yaml
alalc-guj-Gujr-Latn-1997.yaml
alalc-guj-Gujr-Latn-2011.yaml
alalc-hin-Deva-Latn-1997.yaml
alalc-hin-Deva-Latn-2011.yaml
alalc-kat-Geok-Latn-1997.yaml
alalc-kat-Geor-Latn-1997.yaml
alalc-kor-Hang-Latn-1997.yaml
alalc-mal-Mlym-Latn-1997.yaml
alalc-mal-Mlym-Latn-2012.yaml
alalc-mar-Deva-Latn-1997.yaml
alalc-mar-Deva-Latn-2011.yaml
alalc-mkd-Cyrl-Latn-1997.yaml
alalc-mkd-Cyrl-Latn-2013.yaml
alalc-mon-Cyrl-Latn-1997.yaml
alalc-pan-Guru-Latn-1997.yaml
alalc-pan-Guru-Latn-2011.yaml
alalc-per-Arab-Latn-1997.yaml
alalc-pli-Deva-Latn-2012.yaml
alalc-pra-Deva-Latn-2012.yaml
alalc-rus-Cyrl-Latn-1997.yaml
alalc-rus-Cyrl-Latn-2012.yaml
alalc-san-Deva-Latn-2012.yaml
alalc-sin-Sinh-Latn-1997.yaml
alalc-sin-Sinh-Latn-2011.yaml
alalc-srp-Cyrl-Latn-1997.yaml
alalc-srp-Cyrl-Latn-2013.yaml
alalc-tam-Taml-Latn-1997.yaml
alalc-tam-Taml-Latn-2011.yaml
alalc-ukr-Cyrl-Latn-1997.yaml
alalc-ukr-Cyrl-Latn-2011.yaml

**Comment by webdev778** [comment]
PR #27
