### ISSUE TITLE
Urdu System `un-urd-Arab-Latn-1972`

### ISSUE THREAD

**Issue by webdev778** [interscript/jsdemo.interscript.com#62]
![image](https://user-images.githubusercontent.com/28761746/101877157-e9ff6f80-3bd0-11eb-8020-e8bf78e06b82.png)

This is either due to the examples wrongly encoded or the systems not working correctly. 

_Originally posted by @ronaldtse in https://github.com/interscript/jsdemo.interscript.com/issues/61#issuecomment-742962622_

**Comment by AhMohsen46** [comment]
Fixed in https://github.com/interscript/jsdemo.interscript.com/pull/71
