### ISSUE TITLE
un-prs-Arab-Latn-1967 system not correctly

### ISSUE THREAD

**Issue by webdev778** [interscript/jsdemo.interscript.com#63]
the system **un-prs-Arab-Latn-1967** seems not working properly
* js 
![image](https://user-images.githubusercontent.com/28761746/101859730-a0eaf380-3baf-11eb-9028-6e176716539b.png)

* ruby 
![image](https://user-images.githubusercontent.com/28761746/101859754-aba58880-3baf-11eb-9ff2-4b0627ac7c28.png)
![image](https://user-images.githubusercontent.com/28761746/101859756-ae07e280-3baf-11eb-9963-cea9cce69fd8.png)

_Originally posted by @webdev778 in https://github.com/interscript/jsdemo.interscript.com/issues/56#issuecomment-742950436_

**Comment by AhMohsen46** [comment]
checking it now

**Comment by AhMohsen46** [comment]
fixed in https://github.com/interscript/jsdemo.interscript.com/pull/71
