### ISSUE TITLE
Add BGN/PCGN poster page

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#7]
Similar to interscript/interscript.com#10 , we should make a BGN/PCGN poster page with samples.

Systems available: https://github.com/interscript/interscript/issues/493

**Comment by webdev778** [comment]
Add BGN/PCGN Poster Example page, almost systems are to be implemented.

**Comment by ronaldtse** [comment]
@webdev778 can you make a different tab for BGN/PCGN? So users can choose "UN" vs "BGN/PCGN", etc. Thanks.

**Comment by ronaldtse** [comment]
~~Also, the current listing is based on the UN poster -- we have to change them to list all BGN/PCGN systems, and~~
the examples should be taken from the BGN/PCGN systems (the first test is good enough).

(updated: I missed the current list of systems, which is actually correct -- sorry!)

**Comment by ronaldtse** [comment]
Actually there is a problem with the listing -- it's not listing all systems from BGN/PCGN (or just BGN). For example, many of these systems are not shown:
https://github.com/interscript/interscript/issues?q=is%3Aissue+is%3Aclosed+bgn

**Comment by webdev778** [comment]
> @webdev778 can you make a different tab for BGN/PCGN? So users can choose "UN" vs "BGN/PCGN", etc. Thanks.

like interscript.com?

**Comment by ronaldtse** [comment]
Sure!

**Comment by webdev778** [comment]
> Actually there is a problem with the listing -- it's not listing all systems from BGN/PCGN (or just BGN). For example, many of these systems are not shown:
> https://github.com/interscript/interscript/issues?q=is%3Aissue+is%3Aclosed+bgn

I worked based on the list interscript/interscript#493. so should I add all bgn/pcgn in the maps?

**Comment by ronaldtse** [comment]
Yes please -- interscript/interscript#493 only lists out systems that haven't been implemented :wink:

**Comment by webdev778** [comment]
Add tabs

**Comment by webdev778** [comment]
Add all bgn/pcgn systems

**Comment by AhMohsen46** [comment]
@ronaldtse should I still get the arab systems in https://github.com/interscript/interscript/issues/493 done?

**Comment by ronaldtse** [comment]
@AhMohsen46 yes please! This task is only for adding the page. We will still need to add the missing systems (in interscript and in the demo).
