### ISSUE TITLE
Display a sample per system in the text box so people can easily try the gem out

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#73]
We can take the first test for each system and place it in the text box once the system is selected so people can just click on "convert" to test out without needing to know how to type the language.

**Comment by ronaldtse** [comment]
i.e. instead of this,

<img width="907" alt="Screen Shot 2021-01-23 at 1 50 15 PM" src="https://user-images.githubusercontent.com/11865/105570073-f0613980-5d81-11eb-8297-e374c44ebb63.png">

we should have this:

<img width="901" alt="Screen Shot 2021-01-23 at 1 51 33 PM" src="https://user-images.githubusercontent.com/11865/105570105-1e467e00-5d82-11eb-9937-8e77b28f4822.png">

NOTE: I noticed that this particular system (`bgnpcgn-zho-Hans-Latn-1979`) has no tests... ughhhhh.....

**Comment by webdev778** [comment]
I think it's very useful suggestion for better UX/UI, let me modify it.
